### ISSUE TITLE
Rendering with Handlebars

### ISSUE THREAD

**Issue by ghost** [cristiandouce/mongoose-gravatar#4]
When I try to render with {{ model.gravatar }} I get a default image.
When I try to render with {{ model.gravatar() }} I get an error.
When  I console out the output from model.gravatar() I get the correct URL.

What am I missing? Is this perhaps a handlebars restriction?

**Comment by cristiandouce** [comment]
I think it has something to do with how they print methods: http://handlebarsjs.com/#helpers

Not sure though, never used mongoose models with handlebars. Sorry.

**Comment by ghost** [comment]
OK, no worries. For those that come here for the same reason I have created a custom helper to sort it

```
helpers: {
        grav: function (obj) { return obj.gravatar(); },
    }
```

**Comment by cristiandouce** [comment]
:smile: Thanks!
